---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - ack
  - autoconf
  - buf
  - cmake
  - eigen
  - ffmpeg
  - fzf
  - gcc
  - gh
  - git
  - github/gh/gh
  - gnu-sed
  - gnupg
  - go
  - gpg
  - grpc
  - imagemagick
  - jq
  - lazygit
  - lua
  - neovim
  - nmap
  - node
  - opencv
  - openssl
  - pandoc
  - poppler
  - protobuf
  - protoc-gen-go-grpc
  - python@3.11
  - qrencode
  - readline
  - ripgrep
  - speedtest-cli
  - sqlite
  - stow
  - tmux
  - tree
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - blender
  - cardhop
  - cloudcompare
  - docker
  - drawio
  - font-jetbrains-mono-nerd-font
  - font-roboto-mono-nerd-font
  - gimp
  - google-chrome
  - google-cloud-sdk
  - insomnia
  - iterm2
  - karabiner-elements
  - librecad
  - mactex-no-gui
  - meshlab
  - musescore
  - rectangle
  - signal
  - spotify
  - xmind
  - youtube-to-mp3

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1440147259, name: "AdGuard for Safari (1.11.14)" }
  - { id: 823766827, name: "OneDrive (23.147.0716)" }
  - { id: 975937182, name: "Fantastical (3.7.17)" }
  - { id: 363738376, name: "forScore (14.0.3)" }
  - { id: 1451685025, name: "WireGuard (1.0.16)" }
  - { id: 1480933944, name: "Vimari (2.1.1)" }
  - { id: 634148309, name: "Logic Pro (10.7.9)" }
  - { id: 1290358394, name: "Cardhop (2.2.9)" }

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
